"use client";
import { Download } from "lucide-react";
import { useCallback, useEffect, useState } from "react";
import { API_BASE, ApiError, getJson, postJson } from "@/lib/api";
import { useIsPractice } from "@/components/panels/kit";

interface Pack { id: string; label: string; table: string; about: string; loaded: boolean }

/** Made-up practice datasets generated by code with a fixed seed. Practice workspace only. */
export function PacksCard({ onLoaded }: { onLoaded: () => void }) {
  const practice = useIsPractice();
  const [packs, setPacks] = useState<Pack[]>([]);
  const [busy, setBusy] = useState<string | null>(null);
  const [msg, setMsg] = useState<{ ok: boolean; text: string } | null>(null);
  const load = useCallback(() => { getJson<{ packs: Pack[] }>("/api/packs").then((r) => setPacks(r.packs)).catch(() => { /* optional */ }); }, []);
  useEffect(() => { load(); }, [load]);
  if (!practice) return null;
  async function add(p: Pack) {
    setBusy(p.id); setMsg(null);
    try { const r = await postJson<{ rows: number; table: string }>(`/api/packs/${p.id}/load`, {}); setMsg({ ok: true, text: `Loaded ${r.rows.toLocaleString()} rows into ${r.table}.` }); load(); onLoaded(); }
    catch (e) { setMsg({ ok: false, text: e instanceof ApiError ? e.message : "Couldn't load the pack." }); }
    finally { setBusy(null); }
  }
  return (
    <section className="card space-y-3 p-5" aria-label="Sample data packs">
      <h2 className="text-lg font-semibold">Sample data packs</h2>
      <p className="text-sm text-muted">Made-up datasets for practice, created by code with a fixed seed (the same rows every time, nothing downloaded). Loading one replaces its own table only.</p>
      <ul className="grid gap-3 md:grid-cols-3">
        {packs.map((p) => (
          <li key={p.id} className="flex flex-col gap-2 rounded-md border border-line p-3 text-sm">
            <b>{p.label}</b><span className="text-xs text-muted">{p.about}</span>
            <code className="text-xs">{p.table}</code>
            <button className="btn mt-auto self-start" onClick={() => add(p)} disabled={busy !== null}>{busy === p.id ? "Loading…" : p.loaded ? "Reload" : "Load"}</button>
          </li>
        ))}
      </ul>
      {msg && <p role={msg.ok ? "status" : "alert"} className="text-sm" style={{ color: msg.ok ? "var(--good)" : "var(--bad)" }}>{msg.text}</p>}
    </section>
  );
}

/** One zip with every table as CSV plus your settings. API keys are never included. */
export function ExportEverything() {
  return (
    <section className="card space-y-2 p-5" aria-label="Export everything">
      <h2 className="text-lg font-semibold">Export everything</h2>
      <p className="text-sm text-muted">One zip with every table of the active workspace as CSV, plus your KPIs, quality rules, pipelines, workflows, sources and views as JSON. API keys and passwords are not included (they stay in backend/.env). The zip is not encrypted.</p>
      <a className="btn btn-primary inline-flex" href={`${API_BASE}/api/export-all`} download><Download className="h-4 w-4" aria-hidden /> Download everything (.zip)</a>
    </section>
  );
}
