"""Sample data packs: small, made-up datasets for practice, generated by code with a fixed seed so everyone gets the same rows.
Nothing is downloaded. Practice workspace only, so made-up rows never land in Real. Each pack imports as its own table."""
from __future__ import annotations

import random
from datetime import date, timedelta

from app.services import datasets, state, workspaces


class PackError(Exception):
    def __init__(self, message: str, status: int = 400):
        super().__init__(message)
        self.message, self.status = message, status


START = date(2025, 1, 1)


def _retail(r: random.Random):
    stores = ["Downtown", "Harbor", "Westside", "Airport"]
    prods = [("Coffee beans", 14.0), ("Mug", 9.5), ("Tea sampler", 18.0), ("Grinder", 45.0), ("Gift card", 25.0)]
    rows = []
    for d in range(180):
        day = START + timedelta(days=d)
        for s in stores:
            for p, price in prods:
                base = 8 + (4 if day.weekday() >= 5 else 0) + (6 if day.month == 12 else 0)
                units = max(0, int(r.gauss(base, 3)))
                rows.append([day.isoformat(), s, p, str(units), f"{price:.2f}", f"{units * price:.2f}"])
    return ["sale_date", "store", "product", "units", "unit_price", "revenue"], rows


def _saas(r: random.Random):
    plans = [("Starter", 29), ("Team", 99), ("Business", 299)]
    rows = []
    for i in range(1, 801):
        plan, mrr = r.choices(plans, weights=[6, 3, 1])[0]
        start = START + timedelta(days=r.randint(0, 400))
        churned = r.random() < {"Starter": 0.35, "Team": 0.2, "Business": 0.1}[plan]
        end = start + timedelta(days=r.randint(30, 300)) if churned else None
        rows.append([f"C{i:04d}", plan, str(mrr), start.isoformat(), end.isoformat() if end else "", "churned" if churned else "active"])
    return ["customer_id", "plan", "mrr", "start_date", "churn_date", "status"], rows


def _snf(r: random.Random):
    units = [("North wing", 30), ("South wing", 28), ("Memory care", 18)]
    rows = []
    for d in range(120):
        day = START + timedelta(days=d)
        for u, beds in units:
            occ = min(beds, max(0, int(r.gauss(beds * 0.86, 1.5))))
            rows.append([day.isoformat(), "Riverside Care", u, str(beds), str(occ), str(r.choice([0, 0, 1, 1, 2])), str(r.choice([0, 0, 1, 1, 2])),
                         str(1 if r.random() < 0.06 * occ / beds * 3 else 0), f"{max(0.0, r.gauss(14 if u != 'Memory care' else 22, 4)):.1f}"])
    return ["census_date", "facility", "unit", "beds", "occupied", "admits", "discharges", "falls", "agency_hours"], rows


PACKS = {
    "retail": {"label": "Retail sales", "table": "pack_retail_sales", "fn": _retail, "seed": 11,
               "about": "4 stores x 5 products x 180 days. Try revenue by store, weekday patterns, December lift."},
    "saas": {"label": "SaaS subscriptions", "table": "pack_saas_subscriptions", "fn": _saas, "seed": 22,
             "about": "800 customers on 3 plans with churn. Try MRR by plan, churn rate, cohort by start month."},
    "snf": {"label": "Skilled nursing census", "table": "pack_snf_census", "fn": _snf, "seed": 33,
            "about": "3 units x 120 days of occupancy, admits, discharges, falls and agency hours. Made-up numbers, no resident data."},
}


def catalog() -> list[dict]:
    have = {t["table_name"] for t in datasets.list_tables()}
    return [{"id": k, "label": v["label"], "table": v["table"], "about": v["about"], "loaded": v["table"] in have} for k, v in PACKS.items()]


def generate(pack: str) -> tuple[list[str], list[list[str]]]:
    if pack not in PACKS:
        raise PackError("Unknown pack.", 404)
    p = PACKS[pack]
    return p["fn"](random.Random(p["seed"]))


def load(pack: str) -> dict:
    if workspaces.active() != "practice":
        raise PackError("Sample packs only load into the Practice workspace, so made-up rows never mix with Real data.", 409)
    header, rows = generate(pack)
    out = datasets.import_rows(header, rows, PACKS[pack]["table"], "replace", source="sample pack")
    state.audit("pack_load", f"{pack}: {out['rows']} rows")
    return out
