export interface QuizQuestion { id: string; topic: string; q: string; options: string[]; answer: number; why: string }

export const TOPICS = ["KPIs & metrics", "Analytics types", "Data & methods", "ETL / ELT", "Star schema", "Measures", "SCD", "File formats", "Languages & tools", "Visualization"] as const;

export const QUESTIONS: QuizQuestion[] = [
  { id: "k1", topic: "KPIs & metrics", q: "What makes a metric a KPI?", options: ["It is calculated with SQL", "It is tied to a business goal with a target", "It is shown on a chart", "It has more than one dimension"],
    answer: 1, why: "A metric is any measurement. A KPI is a metric linked to a goal, usually with a target, a time window and a threshold for good or bad." },
  { id: "k2", topic: "KPIs & metrics", q: "Revenue is up 12% but the margin fell from 40% to 31%. What is the most useful reading?", options: ["Great quarter: revenue is what matters", "Growth is costing more than it brings in; investigate cost", "The margin number must be wrong", "Nothing, they measure different things"],
    answer: 1, why: "Looking at one KPI alone can mislead. A falling margin alongside rising revenue suggests costs grew faster, so look at cost drivers." },
  { id: "a1", topic: "Analytics types", q: "'Why did revenue drop last Tuesday?' is which type of analytics?", options: ["Descriptive", "Diagnostic", "Predictive", "Prescriptive"],
    answer: 1, why: "Descriptive = what happened. Diagnostic = why it happened (drill-down, comparisons, anomaly causes)." },
  { id: "a2", topic: "Analytics types", q: "A forecast of next week's revenue with a 95% interval is:", options: ["Descriptive", "Diagnostic", "Predictive", "Prescriptive"],
    answer: 2, why: "Predictive analytics estimates what is likely to happen, using historical patterns." },
  { id: "a3", topic: "Analytics types", q: "'Shift weekend capacity to the busiest entity; est. +$4,200' is:", options: ["Descriptive", "Diagnostic", "Predictive", "Prescriptive"],
    answer: 3, why: "Prescriptive analytics recommends an action (and ideally its expected impact)." },
  { id: "a4", topic: "Analytics types", q: "Which list orders the four types from simplest to most advanced?", options: ["Predictive, descriptive, diagnostic, prescriptive", "Descriptive, diagnostic, predictive, prescriptive", "Diagnostic, descriptive, prescriptive, predictive", "Descriptive, predictive, diagnostic, prescriptive"],
    answer: 1, why: "What happened → why → what will happen → what should we do." },
  { id: "d1", topic: "Data & methods", q: "Which is quantitative data?", options: ["Customer interview transcripts", "Free-text survey comments", "Units processed per day", "Photos of storefronts"],
    answer: 2, why: "Quantitative data is numeric and measurable. Qualitative data is descriptive (words, images, observations) and explains the 'why'." },
  { id: "d2", topic: "Data & methods", q: "When are qualitative methods most helpful alongside the numbers?", options: ["To compute totals faster", "To understand why customers behave a certain way", "To replace dashboards", "To remove outliers"],
    answer: 1, why: "Numbers show what and how much; interviews and comments help explain motivation and context." },
  { id: "e1", topic: "ETL / ELT", q: "What is the main difference between ETL and ELT?", options: ["ELT has no extract step", "ELT loads raw data first and transforms inside the warehouse", "ETL only works with CSV", "ETL is always faster"],
    answer: 1, why: "ETL transforms before loading. ELT loads raw data first and uses the warehouse engine (often SQL) to transform, keeping the raw data available." },
  { id: "e2", topic: "ETL / ELT", q: "An Airflow DAG fails its quality gate. What should happen to the downstream load task?", options: ["It runs anyway", "It is skipped, so bad data never reaches the warehouse", "It runs twice", "Airflow deletes the data"],
    answer: 1, why: "Tasks depend on upstream success. A failed gate stops dependent tasks, which is the point of a gate." },
  { id: "e3", topic: "ETL / ELT", q: "A load that can be re-run safely without creating duplicates is called:", options: ["Incremental", "Idempotent", "Atomic", "Normalized"],
    answer: 1, why: "Idempotent: running it again gives the same result (for example, INSERT OR REPLACE keyed by fact_id)." },
  { id: "s1", topic: "Star schema", q: "In a star schema, what sits in the center?", options: ["A dimension table", "The fact table", "A view of all tables", "The date table"],
    answer: 1, why: "The fact table holds the events and measures, surrounded by dimension tables." },
  { id: "s2", topic: "Star schema", q: "'One row per entity per day' describes the table's:", options: ["Cardinality", "Grain", "Index", "Partition"],
    answer: 1, why: "Grain is what one row represents. Decide it first: everything else follows from it." },
  { id: "s3", topic: "Star schema", q: "Why do many analysts build a separate date dimension?", options: ["Databases can't store dates", "To slice by year, quarter, weekday or holiday without recomputing", "To make facts smaller than 1 KB", "It's required by SQL"],
    answer: 1, why: "A date dimension carries ready-made attributes (quarter, day name, is_weekend) that make time slicing easy and consistent." },
  { id: "m1", topic: "Measures", q: "Which measure is NON-additive?", options: ["Revenue", "Units processed", "Net margin %", "Operational cost"],
    answer: 2, why: "A ratio can't be summed or averaged across groups. Re-compute it as SUM(profit) / SUM(revenue)." },
  { id: "m2", topic: "Measures", q: "Daily inventory level is a classic example of a:", options: ["Additive measure", "Semi-additive measure", "Non-additive measure", "Dimension"],
    answer: 1, why: "Semi-additive: you can add across locations at one moment, but not across time (use last value or average)." },
  { id: "m3", topic: "Measures", q: "Two groups have margins 80% (revenue $100) and 20% (revenue $900). The combined margin is closest to:", options: ["50%", "26%", "80%", "20%"],
    answer: 1, why: "Weighted: (80 + 180) / 1000 = 26%. A simple average (50%) over-weights the small group." },
  { id: "c1", topic: "SCD", q: "In SCD Type 1, when a category changes the old value is:", options: ["Kept in a new row", "Overwritten", "Moved to an archive file", "Stored in the fact table"],
    answer: 1, why: "Type 1 overwrites, which is simple but rewrites history." },
  { id: "c2", topic: "SCD", q: "Which columns identify the versions in SCD Type 2?", options: ["valid_from, valid_to, is_current", "created_by, updated_by", "primary_key only", "row_number"],
    answer: 0, why: "Each version has a date range and a current flag so facts can join on the version valid at that date." },
  { id: "f1", topic: "File formats", q: "Which format stores column types and compresses well for analytics?", options: ["CSV", "TSV", "Parquet", "XML"],
    answer: 2, why: "Parquet is a typed, columnar, compressed format. CSV and TSV are untyped text." },
  { id: "f2", topic: "File formats", q: "A date written as 03/04/2026 in a CSV is a risk because:", options: ["CSV can't hold dates", "It may mean March 4 or April 3 depending on the reader", "Excel deletes it", "It's too short"],
    answer: 1, why: "Text formats don't carry a type. Prefer ISO dates (2026-03-04) to avoid ambiguity." },
  { id: "l1", topic: "Languages & tools", q: "Which tool is an open-source workflow orchestrator?", options: ["Apache Superset", "Apache Airflow", "Apache Parquet", "Apache Spark"],
    answer: 1, why: "Airflow schedules and monitors pipelines. Superset visualizes, Spark processes data, Parquet is a file format." },
  { id: "l2", topic: "Languages & tools", q: "Spark is called 'lazy' because:", options: ["It runs slowly", "Transformations only build a plan until an action runs it", "It skips errors", "It sleeps when idle"],
    answer: 1, why: "Spark records transformations and executes when you call an action like show(), count() or write." },
  { id: "v1", topic: "Visualization", q: "You want to compare 10 entities' profit. The clearest choice is:", options: ["A 3D pie chart", "A sorted bar chart", "A radar chart", "A stacked area chart"],
    answer: 1, why: "Bars are read by length, which people compare accurately. Sorting makes ranking obvious." },
  { id: "v2", topic: "Visualization", q: "In a Z-pattern dashboard layout, where should the most important KPI go?", options: ["Bottom-right", "Top-left", "Center", "In a footer"],
    answer: 1, why: "Readers start at the top-left, sweep across the top, diagonally down, then across the bottom." },
  { id: "v3", topic: "Visualization", q: "Which chart title helps the reader most?", options: ["Revenue by month", "Revenue chart", "Revenue grows 4% a month until June, then flattens", "Figure 3"],
    answer: 2, why: "A headline that states the finding tells the reader what to look for." },
];
